### ISSUE TITLE
Sorry，Why not use the adj_mx.pkl? Is it the random matrix better?

### ISSUE THREAD

**Issue by ghost** [CYBruce/STAWnet#4]

**Comment by CYBruce** [comment]
Thanks @a6518413 . The intuition is that close distance between nodes (or detectors) cannot indicate strong spatial dependencies and nodes that have similar distances can have different impacts. Also, there are circumstances when connections can not entail the relationship when the connections are missing, for the reason that the spatial information sometimes can be unavailable due to secrecy or privacy, and the relations are more complicated than connectivity considering various attributes such as the number of lanes, surrounding environment, and infrastructure conditions. Thus, this study ignores the adj_mx.pkl and uses embedding to model the relationships. It doesn't mean that random matrix is better because we do not use a random matrix in this project.

For your information, you can refer to the [original paper](https://ietresearch.onlinelibrary.wiley.com/doi/10.1049/itr2.12044).
